"""portfolio

Revision ID: 1cc6a0f99c33
Revises: 607025239b07
Create Date: 2021-07-16 17:48:05.867448

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '1cc6a0f99c33'
down_revision = '607025239b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_value', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('owner', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_portfolio_users_id_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_operation',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('portfolio', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('stock_id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('value_by_stock', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('commission', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_portfolio_operation_users_id_created_by'),
    sa.ForeignKeyConstraint(['portfolio'], ['portfolio.id'], name='fk_portfolio_operation_portfolio_id_portfolio'),
    sa.ForeignKeyConstraint(['stock_id'], ['stockmodel.id'], name='fk_portfolio_operation_stockmodel_id_stock_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_stock',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('portfolio', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('stock_id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('owner', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_portfolio_stock_users_id_owner'),
    sa.ForeignKeyConstraint(['portfolio'], ['portfolio.id'], name='fk_portfolio_stock_portfolio_id_portfolio'),
    sa.ForeignKeyConstraint(['stock_id'], ['stockmodel.id'], name='fk_portfolio_stock_stockmodel_id_stock_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_stock')
    op.drop_table('portfolio_operation')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
