"""initial changes

Revision ID: 607025239b07
Revises: 
Create Date: 2021-07-06 06:59:11.692784

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '607025239b07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockmodel',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nemo', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nemo')
    )
    op.create_table('users',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('stockdividendmodel',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('stock_id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('currency', sa.String(length=100), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=16, scale=4), nullable=True),
    sa.Column('paid_amount', sa.DECIMAL(precision=16, scale=4), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stockmodel.id'], name='fk_stockdividendmodel_stockmodel_id_stock_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockvaluemodel',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('stock_id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=16, scale=4), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stockmodel.id'], name='fk_stockvaluemodel_stockmodel_id_stock_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockvaluemodel')
    op.drop_table('stockdividendmodel')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stockmodel')
    # ### end Alembic commands ###
